### ISSUE TITLE
Resetting to help screen

### ISSUE THREAD

**Issue by 2braincells2go** [uddhabh/Notepad5#1]
Hey, really like this simple notepad, just what looking for.

Cannot seem to get the help screen back? Have tried clearing cache and does not work.

Is there any key combinations to reset and get help screen back?

Using in classroom and kids need the help screen on start up:)

Thanks!

**Comment by uddhabh** [comment]
Hi, I'm really glad that you liked it.
Unfortunately there is no key combinations to reset the app. But you may open browser console and type `localStorage.clear()` and open Notepad5 on a new tab to reset it.
And hopefully soon I'll add a shortcut to reset it..

**Comment by 2braincells2go** [comment]
Thank you. Really nice notepad!
